### PR TITLE
Gtk4 typing

### PR DESCRIPTION
**Pull request by mat-xc**
Auto generated typings using https://github.com/pygobject/pygobject-stubs/pull/98

### CODE REVIEW

**Comment by lovetox** [comment]
please remove the generator.py changes, this PR should only contain the Gtk4 changes

**Comment by mat-xc** [comment]
> please remove the generator.py changes, this PR should only contain the Gtk4 changes

Yes of course, this for now is only a show case of #98, if it get merged then I will rebase this. That's why I marked this as Draft. If #98 do not get merged probably I should close this one too.

**Comment by mat-xc** [comment]
I found a bug in the generator. Is it OK if I leave the fix in this MR or should I open a new one?

When I finished my tests I will reformat with `black` and `isort` so the lint should pass

**Comment by mat-xc** [comment]
I am done with this. I also checked for previous commits and applied overrides where needed, to avoid regressions. I'll mark this as ready.

**Comment by lovetox** [comment]
can you please squash the commits for the generator and prefix them with "imprv:"

also squash the all commits into one regarding to the gtk4 file

Thanks

**Comment by mat-xc** [comment]
Is it OK like this?

**Pull request merged**
