### PR TITLE
Fix Gtk types

### PR DESCRIPTION
**Pull request by eggplants**
For [my package](https://github.com/eggplants/pimg), I have added some types to  `Gtk.Clipboard.set_image`, `Gtk.Image.new` and `Gtk.Image.new_from_file`.

Also I have fixed some errors in `Gtk` stub:

- add `AccelGroupFindFunc` and `PageSetupDoneFunc` to suppress warnings
- fix `Gtk.AccelGroup.find`'s `data` parameter
  - `..., data: Optional[Object]` -> `..., *data: Optional[object]`
- fix `Gtk.print_run_page_setup_dialog_async`'s `data` parameter
  - `..., data: Optional[object]` -> `..., *data: Optional[object]`

### CODE REVIEW

**Comment by lovetox** [comment]
- add AccelGroupFindFunc and PageSetupDoneFunc to suppress warnings

What warnings?

Why not use the Callable type to describe the func? ( See how its used already in the codebase )

**Comment by eggplants** [comment]
Pylance says:

In https://github.com/pygobject/pygobject-stubs/blob/88d4f3a141e28894743c923eb05cbcf7e5bad7e4/gi-stubs/repository/Gtk.pyi#L387

```text
"PageSetupDoneFunc" is not definedPylance[reportUndefinedVariable](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)
```

In https://github.com/pygobject/pygobject-stubs/blob/88d4f3a141e28894743c923eb05cbcf7e5bad7e4/gi-stubs/repository/Gtk.pyi#L523:

```text
"AccelGroupFindFunc" is not definedPylance[reportUndefinedVariable](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)
```

**Comment by eggplants** [comment]
> Why not use the Callable type to describe the func? ( See how its used already in the codebase )

To annotate in detail, it is weak to use `Callable`. Is it ok?

```python
# func style
def AccelGroupFindFunc(key: AccelKey, closure: GObject.Closure, *data: Any) -> bool: ...
def PageSetupDoneFunc(page_setup: PageSetup, *data: Any) -> None: ...

# callable style
AccelGroupFindFunc = Callable[..., bool]
PageSetupDoneFunc = Callable[..., None]
```

**Comment by lovetox** [comment]
Im not sure i understand you.

Of course if you dont type any of the arguments of the callable then its not that useful, but what hinders you to type the arguments?

Please read the documentation https://docs.python.org/3/library/typing.html#typing.Callable

**Comment by eggplants** [comment]
Callable can't explain variadic arguments. (*args, **kwargs)

https://stackoverflow.com/questions/66961423

**Comment by lovetox** [comment]
We currently type the data arg with `Optional[Any] = ...` this allows to pass no data or something.

I would say its probably not very common that someone really uses this option and wants to pass multiple args here.
Even if someone wants to pass multiple object here, one can work around it with simply passing a tuple or list of objects.

If someone really needs this someday, we can add simple multiple times `Optional[Any] = ..., Optional[Any] = ..., Optional[Any] = ... `.

**Pull request merged**
