### PR TITLE
Fix generator props

### LINKED ISSUE #123: Property are not typed correctly
Some properties should be typed as `Optional` but aren't. For example `Gtk.Application` `active_window` can be NULL.

Probably all the `Object` properties should be marked as `Optional`.

### PR DESCRIPTION
**Pull request by mat-xc**
I found a way to get `getter` and `setter` for properties.

Regenerated Gtk4 and Adw.

Closes #123

### CODE REVIEW

**Comment by mat-xc** [comment]
I don't know why lint is failing... I rerun black but no changes were provided

**Comment by lovetox** [comment]
you need to use the same black version as the CI, it was upgraded to 23.1

**Comment by mat-xc** [comment]
Oh, I am sorry, there was an error in the setter, could you revert / reopen or should I open a new MR?

**Comment by lovetox** [comment]
do a new MR

**Pull request merged**
