### PR TITLE
typing: Gdk3: Add autogenerated hints

### PR DESCRIPTION
**Pull request by lovetox**

### CODE REVIEW

**Comment by lovetox** [comment]
@mat-xc 

I used the generator on the Gdk3 stubs, and i discovered some problems.

1. We should never use `from gi.repository import cairo` we always want simply `import cairo`
2. Further the Event Sub classes are not optimal. Im not sure we can map this correctly from C, but for example `EventButton` should inherit from `Event`. This is not strictly necessary, but it seems multiple methods on the subclasses are broken, for example get_state() which should simply be the one from Event.get_state() where it is correctly annoted.

**Comment by lovetox** [comment]
i fixed 1. and 3. by improving the generator in this regard.

**Comment by mat-xc** [comment]
>     2. Further the Event Sub classes are not optimal. Im not sure we can map this correctly from C, but for example `EventButton` should inherit from `Event`. This is not strictly necessary, but it seems multiple methods on the subclasses are broken, for example get_state() which should simply be the one from Event.get_state() where it is correctly annoted.

There is no way to intercept this from typelib, AFAIK. [In PyGObject they are treated with an override](https://gitlab.gnome.org/GNOME/pygobject/-/blob/master/gi/overrides/Gdk.py#L261). We should probably do the same.

As a side note, please be careful of this:
```python
_SomeSurface = TypeVar("_SomeSurface", bound=cairo.Surface)
```
since it will be lost on every regeneration, as it is done now.

**Comment by lovetox** [comment]
Hm not sure if its worth to write custom generator code for that, in the time we write this i can simply manually do the stubs. And this code will not be usable for any other lib as its Gdk3 specific.

as for the TypeVar, we have no way to include something like that, our override does not work for that.

And this goes into the same direction, if the generator supplies 95% how much is it worth to invest into the last 5%, every library will add another special case.

**Comment by mat-xc** [comment]
> Hm not sure if its worth to write custom generator code for that, in the time we write this i can simply manually do the stubs. And this code will not be usable for any other lib as its Gdk3 specific.
> 
> as for the TypeVar, we have no way to include something like that, our override does not work for that.
> 
> And this goes into the same direction, if the generator supplies 95% how much is it worth to invest into the last 5%, every library will add another special case.

I was referring to the existing override method, with `# override`, in this case we should override the whole classes. As for the TypeVar maybe you can add some special code as you have already done for `cairo`.

**Comment by lovetox** [comment]
with # override i can only override the class definition, not what methods it contains or?

**Comment by mat-xc** [comment]
It will override the whole class

**Comment by lovetox** [comment]
ah great, i will try that.

**Comment by lovetox** [comment]
Ok everything seems fixed, except adding the type var, but its only one line we live with it and look how often we need something like that before we add a solution

**Pull request merged**
