### PR TITLE
typing: Add Ggit

### PR DESCRIPTION
**Pull request by jtojnar**
These are autogenerated.

### CODE REVIEW

**Comment by lovetox** [comment]
Hi,

if you change generated hints add `# override`

Example:
```
# override
def lookup(self, oid: OId, gtype: Type[_O]) -> Optional[_O]: ...
```

When we later improve the generator, it will not override these custom adjusted lines.

**Comment by jtojnar** [comment]
Should I add it to the `TypeVar` definition too?

**Comment by lovetox** [comment]
no, we have no solution for added typevar definitions yet. We will add something when we decided on how this should look

**Comment by lovetox** [comment]
Can i merge this PR? Or do you need to fix other things?

**Comment by lovetox** [comment]
Ah pipeline fails, please install `black` and `isort`  and run both on your file

**Comment by jtojnar** [comment]
Fixed.

**Pull request merged**
