### PR TITLE
Gtk: Type bindings, Gtk: add missing return type

### PR DESCRIPTION
**Pull request by MrinmoyHaloi**
Added types for bindings. Added missing return types.

### CODE REVIEW

**Comment by MrinmoyHaloi** [comment]
Dont merge it yet. I will add more commits

**Comment by lovetox** [comment]
Instead of List you can use list(), same goes for Dict and Tuple.

this is a python 3.9 feature which is released 1 1/2 years ago so i think we should aim for that version

**Comment by MrinmoyHaloi** [comment]
Doesn't typing module works everywhere ?

**Comment by MrinmoyHaloi** [comment]
So should we use Typing module List, tuple, dict or the one provided by python itself

**Comment by MrinmoyHaloi** [comment]
typing module was introduced at python 3.5. So I guess we should instead use typing module

**Comment by MrinmoyHaloi** [comment]
You can merge it now

**Comment by lovetox** [comment]
Why does it matter when the typing module was introduced?
Its about which python version developers use for development, stubs are only used while developing, not at runtime.

I would not assume every developer is on the latest python version (3.10) so i don’t want to use syntax that is only available there. Python 3.10 is 3 months old and has not landed in any of the stable linux distributions.

python 3.9 on the other hand is 1 1/2 years old and most distributions shipping it, so we can assume most developers using at least that.

This gives us the freedom to use python 3.9 syntax.

As we used already list, dict, tuple around this stub package, it makes not much sense starting now importing the old types List, Dict, Tuple.

**Comment by MrinmoyHaloi** [comment]
Ok. Changing it

**Pull request merged**
