### PR TITLE
typing: Gsk: Add autogenerated typings

### PR DESCRIPTION
**Pull request by mat-xc**

### CODE REVIEW

**Comment by lovetox** [comment]
what went wrong with the formatting here? This file does not look like all the others

**Comment by mat-xc** [comment]
I don't know... I used the same procedure:

1. Run generate
2. Run black
3. Run isort

**Comment by lovetox** [comment]
Can you run the generator again and format again, i experienced this once when i used a black plugin for VS Code.

But if you run black from console it should not format it like that

**Comment by mat-xc** [comment]
> Can you run the generator again and format again, i experienced this once when i used a black plugin for VS Code.
> 
> But if you run black from console it should not format it like that

I run black from console. I tried to re-generate and nothing changes. I don't know what to do...

**Pull request merged**
