### PR TITLE
Added types for functions of AboutDialog, AccelGroup, AccelLabel class methods

### PR DESCRIPTION
**Pull request by MrinmoyHaloi**

### CODE REVIEW

**Comment by MrinmoyHaloi** [comment]
Any idea on why travis ci not working ?

**Comment by MrinmoyHaloi** [comment]
I could write a github action. That will run on every commits or pull requests

**Comment by lovetox** [comment]
yes, a action would be nice, i dont think we need travis, i think we can excecute everything in the action

**Comment by MrinmoyHaloi** [comment]
Yeah. And about those deprecated functions. Those are not deprecated because of gtk 4. There are better equivalents of them. Thats why

**Comment by MrinmoyHaloi** [comment]
Like this one
image

**Comment by MrinmoyHaloi** [comment]
So i guess no need to add stubs for them

**Comment by MrinmoyHaloi** [comment]
Ok I will test a mypy action now on my repository

**Comment by lovetox** [comment]
Deprecation means, the API is removed with the next Major Version. Until then it works as it should.

You should not forget stubs are not only used for developing new applications, its mostly there to type check existing applications and make sure on changes errors are discovered when running CI.

Of course you don’t need to type these methods if you dont feel its of value to you.

**Pull request merged**
