### PR TITLE
imprv: extract class' docstring

### PR DESCRIPTION
**Pull request by Aboghazala**
add gdoc to classes
partial contribution for issue #76

### CODE REVIEW

**Comment by Aboghazala** [comment]
This is a use case of LSB-pyright running on sublime text, showing documentation when hovering on a Gtk class


Untitled

**Comment by lovetox** [comment]
Is this really useful, a wall of text in a tooltip?

**Comment by Aboghazala** [comment]
> Is this really useful, a wall of text in a tooltip?

I agree to some extent it is not that useful in tooltip, but if you right click and select "Goto definition" option it will navigate in stubs file showing class definition with the docs which in my opinion is helpful in this case

**Comment by lovetox** [comment]
Ok lets try it

**Pull request merged**
