### PR TITLE
feat: Add Poppler

### PR DESCRIPTION
**Pull request by principis**
I manually annotated the `Action` class.

### CODE REVIEW

**Comment by lovetox** [comment]
if you annoted something manually you need to mark it like this

```python
# override
class Action(GObject.GBoxed):
...
```

this tells the generator to not override the class definition if we rerun it.

**Comment by principis** [comment]
I've added the `# override` for the Action class and also for the Page.get_size method. The `Size` class I recreated in the second commit does still get removed. Is it possible to solve that?

**Comment by lovetox** [comment]
why was the Size class needed? Is it a namedtuple that is returned?

did you try to add override to the size class?

**Comment by principis** [comment]
Yes, it returns a NamedTuple as far as I know. I used [this PR](https://github.com/pygobject/pygobject-stubs/pull/60) as an example, because I didn't really know how to solve it.

This is what is returned by Page.get_size() :
```python
>>> print(type(page.get_size()))
<class 'conflib.pdf.page._ResultTuple'>

>>> print(page.get_size())
(width=612.0, height=792.0)
```

**Comment by lovetox** [comment]
Ok, i think we just have to think about it for now if we ever regenerate the stubs

**Comment by principis** [comment]
Thanks!

**Pull request merged**
