### PR TITLE
Add types for Gdk.Display and Gdk.Monitor

### PR DESCRIPTION
**Pull request by mswiger**
I added the typing information using these docs:

https://lazka.github.io/pgi-docs/#Gdk-3.0/classes/Display.html#Gdk.Display
https://lazka.github.io/pgi-docs/#Gdk-3.0/classes/Monitor.html#Gdk.Monitor

I wasn't sure exactly how to type the return values for `Gdk.Display.get_maximal_cursor_size` or `Gdk.Display.get_pointer`, so I did not update the typings. Maybe they should be NamedTuples?

### CODE REVIEW

**Comment by wurstsalat3000** [comment]
Both methods return a Tuple. For example: `def get_maximal_cursor_size(self) -> tuple[int, int]`

**Comment by mswiger** [comment]
The fields of the returned tuple have names though:

```
(Pdb) p display.get_maximal_cursor_size()
(width=256, height=256)
```

Fields are `width` and `height`.

```
(Pdb) p display.get_pointer()
(screen=<__gi__.GdkWaylandScreen object at 0x7fc1645abf80 (GdkWaylandScreen at 0x563452d42010)>, x=0, y=0, mask=<flags 0 of type Gdk.ModifierType>)
```

Fields are `screen`, `x`, `y`, and `mask`.

Using a regular tuple would work, but it might be nice to keep these field names. It's just not clear to me what the best way to do this would be. We could explicitly create new types to support these return types, but I'm not sure if that's the right approach. For example:

```python
class Size(NamedTuple):
    width: int
    height: int

def get_maximal_cursor_size(self) -> Size: ...
```

**Comment by lovetox** [comment]
Its a ResultTuple object, but i think it only exists in C code.

A namedtuple would be a bit too misleading as it has many methods that this object does not have

something like this would be more fitting

```
class Size(Tuple[int, int]):
    width: int
    height: int
```

**Comment by mswiger** [comment]
Makes sense! I've updated this branch with `Size` and `Pointer` return types for the `Gdk.Display.get_maximal_cursor_size` and `Gdk.Display.get_pointer`. Does this look like what you were thinking?

As a side note, is there a recommended way of testing these changes? The instructions in `CONTRIBUTING.md` seem incomplete/did not work for me.

**Comment by lovetox** [comment]
what did not work?

There is no way to test your changes, we just do a test that you dont introduce syntax errors, thats why we run mypy on the examples folder.

**Comment by mswiger** [comment]
I see, thanks for the explanation!

**Pull request merged**
