### PR TITLE
change: Use gobject introspection to generate more accurate files

### PR DESCRIPTION
**Pull request by mat-xc**
Use GObject introspection data to generate arguments, subclasses, interfaces, return types, ecc...

I have tried to generate `GLib`, `GObject` and `Adw` and they seems good. I think this generate a better starting point then before. The manual edit should be only necessary for overrides in `pygobject`, where a `# TODO` is written on the file.

### CODE REVIEW

**Comment by lovetox** [comment]
Hi,

Looks good to me.

Please format the file with `black` and rebase, this should fix all errors.

**Comment by mat-xc** [comment]
Thanks @lovetox  to looking into this.

I have added typings for virtual functions and fields of objects and structs. I have also reformatted with `black`.

**Comment by lovetox** [comment]
Are you finished? I think this is a great improvement, it does not need to be 100% correct. The biggest part are the argument names which look good and return values, everything else can be added and adjusted manually with little work when someone needs it.

**Comment by mat-xc** [comment]
> Are you finished? I think this is a great improvement, it does not need to be 100% correct. The biggest part are the argument names which look good and return values, everything else can be added and adjusted manually with little work when someone needs it.

I agree, it not needs to be 100% correct. On the other side if there some error it will be difficult to correct it, once the file has been modified.

Currently I am not entirely satisfied by `Object.props` implementation. `pyright` has hard time understanding which type is the property. Do you have any suggestion on how to implement it?

> please run also isort on your changes

Tomorrow I will run it.

**Comment by mat-xc** [comment]
> We do the same in the Gtk3 file and this works fine for me, i also use pyright, there is no error

I hadn't noticed it :sweat_smile:. 
It seems that it can't understand the type under cursor when I point to the props name. For example `button.props.label` if I hover `label` it says `Unknow`. Tomorrow I will try without the ellipsis.

**Comment by lovetox** [comment]
i just tried it, and this works fine for me.
But how do you install the stubs?

Its tricky because of the build, i didnt investigate yet, but you should uninstall the package

then do `git clean -f -d` to remove the files the build moves around, then install again from source

**Comment by lovetox** [comment]
i think i found the problem and pushed a fix, normally installing with `pip install .` in the source directory should work now

**Comment by mat-xc** [comment]
> i think i found the problem and pushed a fix, normally installing with pip install . in the source directory should work now

Now I'm able to see the props type. Thank for your help :smile: 

I was thinking, what if instead of modify directly the generated file we do something like "shadowing" that with an "override" file? I don't know if it possible with .pyi files, if not maybe we can alter the output of generator.py with a configuration file in yaml (or toml, or json, or ...) so that when it founds a symbol that is defined there it just skip the introspection and simply put what is found inside it. For example:

```python
class ExampleObject:
    def function(self) -> None: ...
    def some_function(self) -> None: ...
```
with this configuration
```yaml
- ExampleObject.some_function: |
    def some_function(self, overridden_method: int) -> None: ...
``` 

will output
```python
class ExampleObject:
    def function(self) -> None: ...
    def some_function(self, overridden_method: int) -> None: ...
```
This way we do not touch the auto generated files so if a bug is found in generator.py we can fix it and generate the file again without losing the manual modifications.
What do you think?

**Comment by mat-xc** [comment]
Since I had some time I have implemented it. You can see the result in #99

**Comment by lovetox** [comment]
I feel this approach makes it harder for people to contribute. It makes the process more complex.

Also the generation file is almost a 1000 line module, i see it as a tool to get a good starting point, but i don't want to implement a process where it *must* be used.

Also i think there is not much more that can be improved.

I would see it differently if the libs would change rapidly and its not doable to maintain the changes by a human. But as it is especially for the large modules like Gtk or GLib, they do not change often, and if, only very minimal changes are made.

**Comment by mat-xc** [comment]
I understand your point, I started this with your exact vision. I agree it made it a little bit harder to contribute. I would agree with you if generator.py was perfect. But I am unsure about this. What if I get the GObject.GValue conversion wrong for example, now we need to check thousand of lines by hand. Check the commits and you see how many errors I have gone through. 

Generator do not *need* to be used. But I can't see why not, honestly. 

The first time is run against a new library it automatically generates an override file, if necessary, so an hypothetical contributor is helped some way.

**Comment by lovetox** [comment]
Its not about using the generator. Its about the workflow to start typing overrides in a yaml file. This makes it impossible for users to easily supply a fix. Further it allows it only if all overrides are correctly applied, something that will also not be true everytime in the future, which then puts an effective halt to any contribution until the generator is fixed or extended.

I simply dont want to put any barriers on users and maintainers to easily supply fixes.

If we find errors, and the generator is improved, changes just have to be merged by hand.

It is very unlikely that an error affects thousands of lines of code.

The GTK4 stubs where 5% typed, now with the generator we are probably very near complete, this is a big improvement, and any small error can be fixed by hand.

So i have to say no at this point to the yaml approach.

**Comment by mat-xc** [comment]
>Its not about using the generator. Its about the workflow to start typing overrides in a yaml file. This makes it impossible for users to easily supply a fix. Further it allows it only if all overrides are correctly applied, something that will also not be true everytime in the future, which then puts an effective halt to any contribution until the generator is fixed or extended.

>I simply dont want to put any barriers on users and maintainers to easily supply fixes.

I have started with the yaml approach only because there is no way (that I am aware of) for shadowing/extending typings with a pyi file. If that was possible it would be great.

>The GTK4 stubs where 5% typed, now with the generator we are probably very near complete, this is a big improvement, and any small error can be fixed by hand.

That's the idea. An override file it's a lot smaller and simpler to maintain than the full file. On the other hand generator has become a monster :japanese_ogre:. Maybe I can try to simplify the generator? I tried to change the logic as little as possible., if I start from scratch I think I can do better.

>So i have to say no at this point to the yaml approach.

I don't like the idea to change a file that is 99% auto generated to fix a couple of lines. If you don't like the yaml approach please lets discuss an alternative idea.

**Comment by lovetox** [comment]
A better way would be in my opinion, if we mark the rows in the pyi file which the generator should not change.

for example simply by putting at the end of the line something like `# override`

Then you can parse the original file to find out what users have changed, and use that information when generating the new file.

**Comment by mat-xc** [comment]
This could be a very good idea.

It could be very difficult to understand the symbol to override without more informations. I though of two solutions:

1. Add more information to the comment, something like `# override <ExampleObject.some_function>`
2. Do not use a comment but a decorator
```python
class ExampleObject:
    @override
    def some_function(self) -> None: ...
```

Implementation wise we can create a new tool `parse.py` that take an existing stubs and generate something more machine friendly like the yaml (this operation is only needed if we need to rerun the generator). Then rerun the generator with the "override file" like now.

`parse.py` should parse the python file with `ast`, search the object through the override decorator or the comment information, and regenerate the code with `ast.unparse` in a string. Then it should dumps the founds overrides in a yaml file.

**Comment by lovetox** [comment]
you cant use a decorator, its code and the stub file is then invalid.

Why would we need to add the class in the comment? Seems trivial to get the class when you parse a file line by line.
the class comes first everything afterwards belongs to the class.

Im not sure we need to generate a file with overrides at all? This file is only used as input to the generator, so the generator can simply call some method and get the output, i see no benefit in storing it on the harddrive.

also why yaml and not simply json, when all you want is a key value store. Its supported by the standard lib and we have a dependency less.

**Comment by mat-xc** [comment]
>you cant use a decorator, its code and the stub file is then invalid.

You are right, my bad.

>Why would we need to add the class in the comment? Seems trivial to get the class when you parse a file line by line.
the class comes first everything afterwards belongs to the class.

```python
class ExampleObject:
    class Props:
        prop: str
        prop1: int
        prop2: str
    def __init__(self,
prop: str, # override
                 prop1: int): ...
    def some_function(self, a: int) -> int: ...
```
In this situation it will be pretty hard understand that the override should override the `__init__`

**Comment by mat-xc** [comment]
>Im not sure we need to generate a file with overrides at all? This file is only used as input to the generator, so the generator can simply call some method and get the output, i see no benefit in storing it on the harddrive.

>also why yaml and not simply json, when all you want is a key value store. Its supported by the standard lib and we have a dependency less.

Yes we can pass data through memory, it is only to understand the data flow

**Comment by lovetox** [comment]
Your previous approach would not allow to override single arguments inside a method, and i think its not necessary

Either a method is touched by a human then its the whole method that has the override, so the whole init in this case, the override must go at the end.

**Comment by mat-xc** [comment]
Sorry, I was not referring to overriding a single argument. My objection was that it is actually difficult to understand that the override should be associated with `__init__`. Even if the override is at the end.

One solution can be to put the override on the line before. Like:

```python
class ExampleObject:
    class Props:
        prop: str
        prop1: int
        prop2: str
    # override
    def __init__(self,
prop: str,
                 prop1: int): ...
    def some_function(self, a: int) -> int: ...
```

Then we search for the line below `def __init__(self,` for some regex that should identify at least:
1. `class XXX`
2. `def XXX`
3. `XXX: int ...`

Once we found XXX the problem is to find the parent, tho

**Comment by lovetox** [comment]
I dont see the problem, you parse line by line, you know how a class looks, you know that python indentation with spaces tells you what belongs to the class.

Of course if you simply parse the file with a regex match, you will have a hard time finding the parent.

**Comment by mat-xc** [comment]
You are right, I was thinking of search the `override` string then parse backward. Going line to line from the top we can keep track of every parents while we go through.

All right then. We put a string on the top of the overridden method and scan the file line by line from the top. In the next days I will work on this.

Thank you very much!

**Comment by lovetox** [comment]
BTW i think i found a case where the generator misses something

All classes for example who inherit from Orientable in the GTK4 file, missing the properties of that class which you can pass to the init

Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL) for example should work in Gtk4

**Comment by mat-xc** [comment]
I forgot to check for interfaces properties when generating object props. I will work on this tomorrow.

This is an example of why I insisted for being able to regenerate the file without losing manual modifications.

**Comment by mat-xc** [comment]
Here we are, added the parsing tool for overrides

**Comment by lovetox** [comment]
So is this now ready to merge?

**Comment by mat-xc** [comment]
Yes, I have no other functionality in mind

**Pull request merged**
