### PR TITLE
added github action for mypy test and added more tests

### PR DESCRIPTION
**Pull request by MrinmoyHaloi**

### CODE REVIEW

**Comment by MrinmoyHaloi** [comment]
The action will run on push to all branches and pull requests. It uses python 3.7.12. It will run mypy against the example folder. I have added more things to the example file. You should add more @lovetox

**Comment by MrinmoyHaloi** [comment]
Should i also make a flake8 action ?

**Comment by lovetox** [comment]
if we add something it does not need to be in new actions, all python tests can be added to this action, i dont think we need the flake8 thing right now.

**Comment by MrinmoyHaloi** [comment]
> if we add something it does not need to be in new actions, all python tests can be added to this action, i dont think we need the flake8 thing right now.

ok

**Pull request merged**
