### PR TITLE
typing: Gio: Add autogenerated hints

### PR DESCRIPTION
**Pull request by mat-xc**

### CODE REVIEW

**Comment by lovetox** [comment]
As i maintain myself a bigger codebase that uses Gtk3 and Gio, this flushed out multiple problems with the stubs (read regressions)

I post the result here, tell me if you cant figure out some of the errors, others should be pretty easy (probably inheritence)

```bash
/home/lovetox/projects/gajim/gajim/common/application.py
  /home/lovetox/projects/gajim/gajim/common/application.py:107:31 - error: Cannot access member "connect" for type "NetworkMonitor"
    Member "connect" is unknown (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/common/application.py:107:9 - error: Type of "connect" is unknown (reportUnknownMemberType)
/home/lovetox/projects/gajim/gajim/common/dbus/location.py
  /home/lovetox/projects/gajim/gajim/common/dbus/location.py:111:9 - error: Type of "new" is partially unknown
    Type of "new" is "(desktop_id: str, accuracy_level: AccuracyLevel, cancellable: Cancellable | None, callback: Unknown, user_data: Any | None = ...) -> Simple" (reportUnknownMemberType)
/home/lovetox/projects/gajim/gajim/common/dbus/logind.py
  /home/lovetox/projects/gajim/gajim/common/dbus/logind.py:55:13 - error: Argument of type "(connection: DBusConnection, name: str, name_owner: str, *_user_data: Any) -> None" cannot be assigned to parameter "name_appeared_closure" of type "Closure | None" in function "bus_watch_name"
    Type "(connection: DBusConnection, name: str, name_owner: str, *_user_data: Any) -> None" cannot be assigned to type "Closure | None"
      "object" is incompatible with "Closure"
      Type cannot be assigned to type "None" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/common/dbus/logind.py:56:13 - error: Argument of type "(_connection: DBusConnection, name: str, *_user_data: Any) -> None" cannot be assigned to parameter "name_vanished_closure" of type "Closure | None" in function "bus_watch_name"
    Type "(_connection: DBusConnection, name: str, *_user_data: Any) -> None" cannot be assigned to type "Closure | None"
      "object" is incompatible with "Closure"
      Type cannot be assigned to type "None" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/common/dbus/logind.py:104:16 - error: Condition will always evaluate to False since the types "Tuple[Variant, UnixFDList]" and "None" have no overlap (reportUnnecessaryComparison)
/home/lovetox/projects/gajim/gajim/common/dbus/remote_control.py
  /home/lovetox/projects/gajim/gajim/common/dbus/remote_control.py:142:13 - error: Arguments missing for parameters "get_property_closure", "set_property_closure" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/common/dbus/remote_control.py:161:35 - error: "get" is not a known member of "None" (reportOptionalMemberAccess)
/home/lovetox/projects/gajim/gajim/common/preview_helpers.py
  /home/lovetox/projects/gajim/gajim/common/preview_helpers.py:456:58 - error: Argument of type "bytes | None" cannot be assigned to parameter "data" of type "list[int] | None" in function "content_type_guess"
    Type "bytes | None" cannot be assigned to type "list[int] | None"
      Type "bytes" cannot be assigned to type "list[int] | None"
        "bytes" is incompatible with "list[int]"
        Type cannot be assigned to type "None" (reportGeneralTypeIssues)
/home/lovetox/projects/gajim/gajim/gtk/application.py
  /home/lovetox/projects/gajim/gajim/gtk/application.py:111:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:118:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:125:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:133:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:164:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:171:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:179:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:186:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:192:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:376:9 - error: Argument missing for parameter "cancellable" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:428:17 - error: Cannot access member "connect" for type "Action"
    Member "connect" is unknown (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:428:13 - error: Type of "connect" is unknown (reportUnknownMemberType)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:465:17 - error: Cannot access member "connect" for type "Action"
    Member "connect" is unknown (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:465:13 - error: Type of "connect" is unknown (reportUnknownMemberType)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:475:16 - error: Cannot access member "set_enabled" for type "Action"
    Member "set_enabled" is unknown (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:475:9 - error: Type of "set_enabled" is unknown (reportUnknownMemberType)
/home/lovetox/projects/gajim/gajim/gtk/builder.py
  /home/lovetox/projects/gajim/gajim/gtk/builder.py:77:27 - error: Cannot access member "decode" for type "list[int]"
    Member "decode" is unknown (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/builder.py:77:16 - error: Type of "decode" is unknown (reportUnknownMemberType)
  /home/lovetox/projects/gajim/gajim/gtk/builder.py:77:16 - error: Return type is unknown (reportUnknownVariableType)
/home/lovetox/projects/gajim/gajim/gtk/chat_action_processor.py
  /home/lovetox/projects/gajim/gajim/gtk/chat_action_processor.py:277:19 - error: Argument missing for parameter "expected_type" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/chat_action_processor.py:277:9 - error: Type of "variant" is unknown (reportUnknownVariableType)
  /home/lovetox/projects/gajim/gajim/gtk/chat_action_processor.py:279:28 - error: Type of "get_string" is unknown (reportUnknownMemberType)
  /home/lovetox/projects/gajim/gajim/gtk/chat_action_processor.py:279:28 - error: Argument type is unknown
    Argument corresponds to parameter "selected_action" in function "_replace_text" (reportUnknownArgumentType)
  /home/lovetox/projects/gajim/gajim/gtk/chat_action_processor.py:293:27 - error: Argument missing for parameter "expected_type" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/chat_action_processor.py:293:17 - error: Type of "variant" is unknown (reportUnknownVariableType)
  /home/lovetox/projects/gajim/gajim/gtk/chat_action_processor.py:295:24 - error: Type of "get_string" is unknown (reportUnknownMemberType)
  /home/lovetox/projects/gajim/gajim/gtk/chat_action_processor.py:295:24 - error: Return type is unknown (reportUnknownVariableType)
/home/lovetox/projects/gajim/gajim/gtk/chat_stack.py
  /home/lovetox/projects/gajim/gajim/gtk/chat_stack.py:491:20 - error: Cannot access member "connect" for type "Action"
    Member "connect" is unknown (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/chat_stack.py:491:13 - error: Type of "connect" is unknown (reportUnknownMemberType)
/home/lovetox/projects/gajim/gajim/gtk/main.py
  /home/lovetox/projects/gajim/gajim/gtk/main.py:169:16 - error: Expression of type "Action" cannot be assigned to return type "SimpleAction"
    "Action" is incompatible with "SimpleAction" (reportGeneralTypeIssues)
/home/lovetox/projects/gajim/gajim/gtk/notification_manager.py
  /home/lovetox/projects/gajim/gajim/gtk/notification_manager.py:96:20 - error: Cannot access member "set_enabled" for type "Action"
    Member "set_enabled" is unknown (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/notification_manager.py:96:9 - error: Type of "set_enabled" is unknown (reportUnknownMemberType)
  /home/lovetox/projects/gajim/gajim/gtk/notification_manager.py:101:18 - error: Cannot access member "set_enabled" for type "Action"
    Member "set_enabled" is unknown (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/notification_manager.py:101:9 - error: Type of "set_enabled" is unknown (reportUnknownMemberType)
  /home/lovetox/projects/gajim/gajim/gtk/notification_manager.py:106:22 - error: Cannot access member "set_enabled" for type "Action"
    Member "set_enabled" is unknown (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/notification_manager.py:106:9 - error: Type of "set_enabled" is unknown (reportUnknownMemberType)
  /home/lovetox/projects/gajim/gajim/gtk/notification_manager.py:111:19 - error: Cannot access member "set_enabled" for type "Action"
    Member "set_enabled" is unknown (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/notification_manager.py:111:9 - error: Type of "set_enabled" is unknown (reportUnknownMemberType)
  /home/lovetox/projects/gajim/gajim/gtk/notification_manager.py:116:20 - error: Cannot access member "set_enabled" for type "Action"
    Member "set_enabled" is unknown (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/notification_manager.py:116:9 - error: Type of "set_enabled" is unknown (reportUnknownMemberType)
/home/lovetox/projects/gajim/gajim/gtk/roster.py
  /home/lovetox/projects/gajim/gajim/gtk/roster.py:150:26 - error: Variable "func" is not accessed (reportUnusedVariable)
/home/lovetox/projects/gajim/gajim/gtk/util.py
  /home/lovetox/projects/gajim/gajim/gtk/util.py:897:12 - error: Argument missing for parameter "detailed_action" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/util.py:897:5 - error: Type of "item" is unknown (reportUnknownVariableType)
  /home/lovetox/projects/gajim/gajim/gtk/util.py:900:9 - error: Type of "set_action_and_target_value" is unknown (reportUnknownMemberType)
  /home/lovetox/projects/gajim/gajim/gtk/util.py:901:16 - error: Return type is unknown (reportUnknownVariableType)
  /home/lovetox/projects/gajim/gajim/gtk/util.py:903:12 - error: Argument missing for parameter "detailed_action" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/util.py:903:5 - error: Type of "item" is unknown (reportUnknownVariableType)
  /home/lovetox/projects/gajim/gajim/gtk/util.py:905:9 - error: Type of "set_action_and_target_value" is unknown (reportUnknownMemberType)
  /home/lovetox/projects/gajim/gajim/gtk/util.py:907:9 - error: Type of "set_action_and_target_value" is unknown (reportUnknownMemberType)
  /home/lovetox/projects/gajim/gajim/gtk/util.py:909:9 - error: Type of "set_action_and_target_value" is unknown (reportUnknownMemberType)
  /home/lovetox/projects/gajim/gajim/gtk/util.py:910:12 - error: Return type is unknown (reportUnknownVariableType)

```

**Comment by mat-xc** [comment]
Some analysis, to get started. My responses prefixed with >

```
/home/lovetox/projects/gajim/gajim/common/application.py
  /home/lovetox/projects/gajim/gajim/common/application.py:107:31 - error: Cannot access member "connect" for type "NetworkMonitor"
    Member "connect" is unknown (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/common/application.py:107:9 - error: Type of "connect" is unknown (reportUnknownMemberType)

> NetworkMonitor is not a GObject is an Interface I think the stub is correct

/home/lovetox/projects/gajim/gajim/common/dbus/location.py
  /home/lovetox/projects/gajim/gajim/common/dbus/location.py:111:9 - error: Type of "new" is partially unknown
    Type of "new" is "(desktop_id: str, accuracy_level: AccuracyLevel, cancellable: Cancellable | None, callback: Unknown, user_data: Any | None = ...) -> Simple" (reportUnknownMemberType)
  
> ???

/home/lovetox/projects/gajim/gajim/common/dbus/logind.py
  /home/lovetox/projects/gajim/gajim/common/dbus/logind.py:55:13 - error: Argument of type "(connection: DBusConnection, name: str, name_owner: str, *_user_data: Any) -> None" cannot be assigned to parameter "name_appeared_closure" of type "Closure | None" in function "bus_watch_name"
    Type "(connection: DBusConnection, name: str, name_owner: str, *_user_data: Any) -> None" cannot be assigned to type "Closure | None"
      "object" is incompatible with "Closure"
      Type cannot be assigned to type "None" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/common/dbus/logind.py:56:13 - error: Argument of type "(_connection: DBusConnection, name: str, *_user_data: Any) -> None" cannot be assigned to parameter "name_vanished_closure" of type "Closure | None" in function "bus_watch_name"
    Type "(_connection: DBusConnection, name: str, *_user_data: Any) -> None" cannot be assigned to type "Closure | None"
      "object" is incompatible with "Closure"
      Type cannot be assigned to type "None" (reportGeneralTypeIssues)

> Probably we should ignore GObject.Closure arguments and override with Callable[..., Any] at least.

  /home/lovetox/projects/gajim/gajim/common/dbus/logind.py:104:16 - error: Condition will always evaluate to False since the types "Tuple[Variant, UnixFDList]" and "None" have no overlap (reportUnnecessaryComparison)

> ???

/home/lovetox/projects/gajim/gajim/common/dbus/remote_control.py
  /home/lovetox/projects/gajim/gajim/common/dbus/remote_control.py:142:13 - error: Arguments missing for parameters "get_property_closure", "set_property_closure" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/common/dbus/remote_control.py:161:35 - error: "get" is not a known member of "None" (reportOptionalMemberAccess)
/home/lovetox/projects/gajim/gajim/common/preview_helpers.py
  /home/lovetox/projects/gajim/gajim/common/preview_helpers.py:456:58 - error: Argument of type "bytes | None" cannot be assigned to parameter "data" of type "list[int] | None" in function "content_type_guess"
    Type "bytes | None" cannot be assigned to type "list[int] | None"
      Type "bytes" cannot be assigned to type "list[int] | None"
        "bytes" is incompatible with "list[int]"
        Type cannot be assigned to type "None" (reportGeneralTypeIssues)

> content_type_guess accept an array of uint8 elements. How can we hint this so that can accept also "bytes"?

 /home/lovetox/projects/gajim/gajim/gtk/application.py:111:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:118:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:125:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:133:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:164:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:171:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:179:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:186:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)
  /home/lovetox/projects/gajim/gajim/gtk/application.py:192:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)

> It seems that you are missing some parameters, is this ok and not a bug?

```

**Comment by lovetox** [comment]
> NetworkMonitor is not a GObject is an Interface I think the stub is correct

Its not correct, https://lazka.github.io/pgi-docs/#Gio-2.0/classes/NetworkMonitor.html#Gio.NetworkMonitor
it has signals, how can i connect to them when there is no connect() method.

In general these errors are from working code, if the error says uknown method connect() it means the code calls connect() and it works, but the stubs dont think it should

**Comment by lovetox** [comment]
> /home/lovetox/projects/gajim/gajim/gtk/application.py:111:9 - error: Argument missing for parameter "arg_description" (reportGeneralTypeIssues)

This is from calling

https://lazka.github.io/pgi-docs/#Gio-2.0/classes/Application.html#Gio.Application.add_main_option

the docs say we need to pass this, but in fact my code works without passing the last arg, not sure how this works anyway.
maybe pygobject fills missing args with None, so implicit all args that come last and are nullable dont need to be passed. But thats just an assumption

**Comment by mat-xc** [comment]
> > NetworkMonitor is not a GObject is an Interface I think the stub is correct
> 
> Its not correct, https://lazka.github.io/pgi-docs/#Gio-2.0/classes/NetworkMonitor.html#Gio.NetworkMonitor it has signals, how can i connect to them when there is no connect() method.
> 
> In general these errors are from working code, if the error says uknown method connect() it means the code calls connect() and it works, but the stubs dont think it should

Can you share an example code of this? 

I suppose that you have typed an object that implements NetworkMonitor only as NetworkMonitor. Implicitly it should be a GObject, otherwise it cannot implement an interface in the first place. So basically every interface should subclass GObject.Object? Is it correct?

**Comment by lovetox** [comment]
```
Python 3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Gio
>>> from gi.repository import GObject
>>> mon = Gio.NetworkMonitor.get_default()
>>> isinstance(mon, GObject.GObject)
True
```

**Comment by mat-xc** [comment]
I am ok with subclassing `GObject.Object` for every interface. But here an example of another problem that could arise.

```python
from gi.repository import Gio, GObject

class Example(Gio.NetworkMonitor):
    example_prop = GObject.Property(type=str, default="example")

e = Example()
```

```
Traceback (most recent call last):
  File "/var/home/matteo/test/test.py", line 4, in <module>
    class Example(Gio.NetworkMonitor):
  File "/usr/lib64/python3.11/site-packages/gi/types.py", line 226, in __init__
    super(GObjectMeta, cls).__init__(name, bases, dict_)
  File "/usr/lib64/python3.11/site-packages/gi/types.py", line 205, in __init__
    cls._type_register(cls.__dict__)
  File "/usr/lib64/python3.11/site-packages/gi/types.py", line 217, in _type_register
    _gi.type_register(cls, namespace.get('__gtype_name__'))
TypeError: argument must be a GObject subclass
```

**Comment by lovetox** [comment]
Your first example is something a type checker cannot catch anyway, its custom magic that pygobject invented to define properties.
for a type checker this looks like a class attribute that is assigned a value. I wouldnt know how a class needs to look like that a type checker disallows to assign a class attribute.

Nothing comes to mind how to express this, maybe its impossible. There are things in C which we cannot model in python.

**Comment by mat-xc** [comment]
Some comments on the changes to generator:

1. Function args that are `Optional` defaults to `None`, if it's possible.
2. Changed the `user_data` argument name so that a function that do not implement all the arguments can still use them with this notation:
```python
object.function(1, 2, callback, user_data="example")
```
3. Array types when they convert from Python -> C are checked with `PySequence_Check()` so they can be any `Sequence`. When they are converted from C -> Python they are `list` for every type but `UINT8` where they are `bytes`
4. Fixed `GSLIST` and `GLIST` typing
5. `GObject.Closure` overridden with a simple `Callable`
6. Interfaces subclass `GObject.Object`

**Comment by lovetox** [comment]
Great, could you move the generator changes to a separate pull request

**Comment by mat-xc** [comment]
> EDIT: Or wait i will check later if we have still erros with these changes.

This would be great, thank you

**Comment by lovetox** [comment]
This was a great improvement we are down to a few errors.

```
    name_appeared_closure: Optional[Callable] = None,
    name_vanished_closure: Optional[Callable] = None,
```

This is invalid, it needs to be Callable[..., Any]

**Comment by lovetox** [comment]
And is it possible to have Gio.AsyncReadyCallback somehow typed and used

**Comment by mat-xc** [comment]
> This was a great improvement we are down to a few errors.
> 
> ```
>     method_call_closure: Optional[Callable] = None,
>     name_appeared_closure: Optional[Callable] = None,
>     name_vanished_closure: Optional[Callable] = None,
> ```
> 
> This is invalid, it needs to be Callable[..., Any]

I thought it was the same. Fixed.

> And is it possible to have Gio.AsyncReadyCallback somehow typed and used
> https://lazka.github.io/pgi-docs/#Gio-2.0/callbacks.html#Gio.AsyncReadyCallback

It doesn't seems to be defied in Python. Could you please provide an example on where it's used?

**Comment by lovetox** [comment]
It defines a function signature

For example https://amolenaar.github.io/pgi-docgen/#Gio-2.0/functions.html#Gio.app_info_get_default_for_type_async

callback expects a function with this specific signature.

Can we discover this or not?

**Comment by mat-xc** [comment]
> It defines a function signature
> 
> For example https://amolenaar.github.io/pgi-docgen/#Gio-2.0/functions.html#Gio.app_info_get_default_for_type_async
> 
> callback expects a function with this specific signature.
> 
> Can we discover this or not?

This should be a FIXME in the generator.

I can't check right now, but if I understand correctly, the problem is that each of this functions takes user_data arguments and I don't think there is a way to describe such signature in Python. It should be something like `Callable[a: int, ..., *user_data: Any]`. So right now it fallback to a generic `Callable[..., RetType]`

**Comment by lovetox** [comment]
i think its possible with python 3.10

`Callable[Concatenate[GObject, AsyncResult, P], Any]`

But currently we support python 3.7, so i guess we leave it like that for now.

**Comment by lovetox** [comment]
Please, rebase this PR and remove the DRAFT status, then i will merge it.

**Pull request merged**
