### PR TITLE
typing: GdkPixbuf: Add autogenerated hints

### PR DESCRIPTION
**Pull request by mat-xc**

### CODE REVIEW

**Comment by lovetox** [comment]
`def get_formats() -> list: ...`

there is the type of the list items missing here, which leads to errors

**Comment by lovetox** [comment]
`def write(self, buf: list[int]) -> bool: ...`

This also looks wrong, list[int] should be `bytes`

**Comment by mat-xc** [comment]
> `def write(self, buf: list[int]) -> bool: ...`
> 
> This also looks wrong, list[int] should be `bytes`

I have tried with Python Repl and actually works with list tuple and bytes. I think the correct typing should be `typing.Iterable` what do you think?

It probably can be extended to every array arguments.

**Comment by mat-xc** [comment]
> `def get_formats() -> list: ...`
> 
> there is the type of the list items missing here, which leads to errors

Here it triggers the `FIXME` because it returns a GSList. I will fix this tomorrow

**Comment by lovetox** [comment]
> While as IN arguments this can be ok, for OUT arguments should we return `list[]` or `Iterable[]` from functions?

Not sure i understand you correctly. Its not ok as method argument, bytes is not a list[int]

and as a return value its even more wrong, iterable only tells me that something is iterable, i need to know that it returns bytes, so i can use byte methods.

**Comment by mat-xc** [comment]
> > While as IN arguments this can be ok, for OUT arguments should we return `list[]` or `Iterable[]` from functions?
> 
> Not sure i understand you correctly. Its not ok as method argument, bytes is not a list[int]
> 
> and as a return value its even more wrong, iterable only tells me that something is iterable, i need to know that it returns bytes, so i can use byte methods.

As arguments I think pygobject treat bytes and list the same way, I need to check but is seems plausible. If that is the case we should treat every input argument as Iterable instead of a list, so you can pass bytes and list the same way.

As return value I think it will return at most list. Maybe there is some special handling for array of uint8 that converts that in bytes, but I don't think

**Comment by lovetox** [comment]
> As return value I think it will return at most list. Maybe there is some special handling for array of uint8 that converts that in bytes, but I don't think

Im not following. You need to return the type of the object that the library actually returns.
If you return a list, this means i can call append() on it. Which would fail, because the lib returns bytes which has no append() method.

**Comment by mat-xc** [comment]
Yes the return value is important, you are right. I just need to check pygobject to understand what actually is returned.

As input parameters do you have any observation against the use of Iterable?

**Comment by lovetox** [comment]
as input, iterable works i guess. Im just not sure if its really right.

I bet if you check pygobject you will see that it converts list of ints, always into bytes.

And from that i think its save to assume it never actually expects a list of ints also for input parameters, it just works by accident.

if you look up the docs, they all say bytes for input and return

https://lazka.github.io/pgi-docs/#GdkPixbuf-2.0/classes/Pixbuf.html#GdkPixbuf.Pixbuf.get_pixels

so the docgen lib seems to know that it needs to show bytes in this case.

**Comment by lovetox** [comment]
I merge this now, im not perfectly happy with iterable[int] instead of bytes, but it does not throw errors, lets see if users complain

**Pull request merged**
