### PR TITLE
Packaging with setup.cfg

### PR DESCRIPTION
**Pull request by eggplants**
I have moved packaging information from setup.py to setup.cfg and added pyproject.toml for supporting both `pip install -e .` and `pip install .`.

Also I have added dev dependencies as extras_require in setup.cfg. This enables to install them with `pip install '.[dev]'`.

### CODE REVIEW

**Comment by lovetox** [comment]
Hi,

Is this MR now ready for review or do you plan any more changes?

**Comment by eggplants** [comment]
No. That's it.

**Comment by eggplants** [comment]
No. Ready for merging.

**Comment by lovetox** [comment]
- Please remove the "fix:" from the commit message and start the commit with a capital letter
- Please factor the change to examples out into its own commit as it has nothing to do with the commit message

Thanks

**Pull request merged**
