### PR TITLE
Added docstrings for important classes and functions

### PR DESCRIPTION
**Pull request by MrinmoyHaloi**
Added docstrings for main, add_from_file, get_object functions. And also for AboutDialog, Application, ApplicationWindow, Box, Grid, Builder, Button, Label, Entry and window classes. The docstrings shows up when hovering over those functions or classes in ide's and code editors. Useful sometimes in my opinion

### CODE REVIEW

**Comment by lovetox** [comment]
Generally i dont want to manually maintain additional to the types also the documentation.

We should apply some tool like https://pypi.org/project/gi-docgen/ to generate the documentation. Then we just need to write a script that applies the docs to the functions.

Im ok with merging a simple sentence per Widget as the chances this gets outdated are none.

Thanks

**Comment by lovetox** [comment]
Can you please squash the commits into one, a simple commit message like Add docstrings is enough

if you want to add more please add it to the extended commit message

**Comment by MrinmoyHaloi** [comment]
I haven't tried gi-docgen. Have you tried ?

**Comment by lovetox** [comment]
this is still considerable work, its not running simply the application.

**Comment by MrinmoyHaloi** [comment]
i am closing the pull request. If we add docstrings this way it will take ages

**Pull request closed without merging**
